name: Build APK with EAS and Update OTA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g eas-cli
          npm install

      - name: Build APK
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Create OTA update
        run: eas update --branch main --platform android --message "Mise à jour automatique via GitHub Actions"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
