name: Build APK with EAS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Vous pouvez adapter la version de Node.js si nécessaire

      # Installer les dépendances
      - name: Install dependencies
        run: |
          npm install -g eas-cli
          npm install

      # Utiliser le token Expo pour se connecter
      - name: Build APK
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  # Utilisation du secret Expo token ici
