name: Deploy OTA Update

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g eas-cli
          npm install

      - name: Publish OTA Update
        run: |
          eas update --branch main --platform android --message "Mise à jour automatique"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
